### ISSUE TITLE
Assembly dependencies conflict

### ISSUE THREAD

**Issue by radumg** [BadMonkeysTeam/Mandrill#32]
Hey @ksobon , i get these errors when opening Dynamo now :

![mandrill assembly issues](https://cloud.githubusercontent.com/assets/11439624/24195432/9fb22b62-0ef1-11e7-8d8d-ea1403fd4481.PNG)

All 4 errors provide the same text when expanded to show details, see the last one.

Is the `EO.WebBrowser` assembly loaded in multiple places ?

**Comment by ksobon** [comment]
I only started getting this error recently when I updated to Revit 2017.1 so I am making an assumption that Revit team is using that same library somewhere....it doesn't cause any issues so you can just ignore it.

**Comment by ksobon** [comment]
So as Dimitar noted on his Twitter account, this is caused by Dynamo Player also using EO.WebBrowser. I guess our versions are conflicting and that's causing reference issue, but not an actual issue. I need to maybe ask Dynamo team to make sure that this doesn't bubble up. There is no need it should.
