### ISSUE TITLE
Window is empty

### ISSUE THREAD

**Issue by DanielHurtubise** [BadMonkeysTeam/Mandrill#35]
Not sure why i get this empty window on a small test file.
Basically doing a chart based on department and Area

![image](https://cloud.githubusercontent.com/assets/4299930/26209330/c6c1e756-3bec-11e7-82dc-e414a321c221.png)

**Comment by DanielHurtubise** [comment]
Same result if i use Code Blocks
![image](https://cloud.githubusercontent.com/assets/4299930/26209514/48343a32-3bed-11e7-9ae8-6e5f22a11c6e.png)

**Comment by ksobon** [comment]
try setting the TickMarks value to something like 3 or just feeding in more data points.

**Comment by DanielHurtubise** [comment]
Nailed it, setting the TickMarks to a Count fixed it :)

**Comment by kevincarv** [comment]
I'm getting the same problem, but in Grasshopper version there is no TickMarks input. 
![image](https://user-images.githubusercontent.com/55897433/68236073-372f0c00-ffe3-11e9-85c4-45509e9229a6.png)

**Comment by ksobon** [comment]
can you post a sample file for me to re-create?

**Comment by kevincarv** [comment]
In fact, I'm using the sample file uploaded here. I'm not sure if it is because I'm using the CSV file from the Dynamo folder..

The Grasshopper (.gh) file - **Folder Samples Grasshopper**:
https://github.com/Ba

dMonkeysTeam/Mandrill/tree/master/_Samples/Grasshopper/ParallelCoordinates

The CSV file - **Folder Samples Dynamo**:
https://github.com/BadMonkeysTeam/Mandrill/blob/master/_Samples/Dynamo/ParallelCoordinatesChart/parallelCoordinatesData.csv

Anyway, here is the file with my try:
[parallelCoordinatesSample.zip](https://github.com/BadMonkeysTeam/Mandrill/files/3814226/parallelCoordinatesSample.zip)

Thanks,
Kevin

**Comment by kevincarv** [comment]
Any news? Are there any pre-requisites to run Mandrill on Rhino?

**Comment by ksobon** [comment]
@kevincarv I opened that file you sent me and I am able to render that chart without any issues: 

![image](https://user-images.githubusercontent.com/529781/69885858-57ce4700-12ad-11ea-9fb6-88ebb71115c2.png)

Please make sure that you have Rhino6, and latest version of Mandrill installed: https://www.food4rhino.com/app/mandrill-dataviz

Cheers!

**Comment by kevincarv** [comment]
I tried in my home pc instead of work pc, and it works. Probably is some kind of network filter from the company. I'll try to unblock it. Thank you!

Can I take the opportunity from this topic to ask you how can I use custom visuals? I saw on your website that you can use D3.js visuals. I would like to use this one: http://bl.ocks.org/robschmuecker/7880033

How do I proceed to use it in grasshopper?

Sorry if this is the wrong place to ask. I can ask in another place, if you want.

Best regards
